### ISSUE TITLE
Design for new request flow.

### ISSUE THREAD

**Issue by fgregg** [datamade/govqa-py#11]
Different instances of GovQA will have custom required fields for new FOIA submissions, and most (all?) have captchas. 

I propose the following design to address this.

```python
class GovQA(...):

    def get_request_form(self) -> RecordRequestForm
        '''build a RecordRequestForm from the govqa's page
        ...

class RecordRequestForm(...):

    schema  # a jsonschema describing the required fields
    captcha # a dictionary containing the information about the captcha

    def submit(self, record_request_dict):
        ...
```

and the flow could go something like this

```python
..
form = gqa.form_request()
solution = some_function_that_gets_a_solution_for_a_captcha(form.captcha)
form.submit({"Describe the Record Requested": "a ham sandwich", "captcha": "solution"})
```

before the submitting to the site, `record_request_dict` would be validated against the jsonschema and give a useful error message if it does not validate.

**Comment by mitchelljkotler** [comment]
This sounds good to me

**Comment by fgregg** [comment]
great! tbc, this library would not implement `some_function_that_gets_a_solution_for_a_captcha`

**Comment by fgregg** [comment]
implemented
