### ISSUE TITLE
Return attachments with time/date updated and unique identifier

### ISSUE THREAD

**Issue by hancush** [datamade/govqa-py#3]
> Attachments return a URL, a content disposition and an expiration date.  Two things that would be useful would be a date/time of when it was posted if available, to help keep track of which ones are new, as well as any sort of unique identifier if it exists, again to keep track of which ones have already been fetched.  I do not think it enforces file names to be unique, so I would like to avoid trying to rely on just the name.

**Comment by fgregg** [comment]
@mitchelljkotler, i couldn't spy anything that looked like a reliable unique identifier, but i have code coming in that adds date the file was uploaded.
